### ISSUE TITLE
Problem with dependencies

### ISSUE THREAD

**Issue by pierre1590** [getapper/generator-g-next#2]
I have the following problem:
![ErrorGetapperGenerator](https://user-images.githubusercontent.com/3288682/175822152-4890352a-0115-45ce-92cc-dd2d959cd6d1.jpg)
How can I fix it?

**Comment by antoniogiordano** [comment]
Hi @pierre1590 , GeNYG (Getapper NextJS Yeoman Generator) is still a WIP project, we are updating commands constantly in the last few days. It looks like you have to update react-hook-form dependencies to work with React@18 I guess.
Try "npm i react-hook-form@latest", it should work, but probably you'll have other dependencies to update as well.
When this GeNYG tool will be more stable I'll ping you, in the meantime you can checkout our GRYG tool  https://github.com/getapper/generator-g-react that is based on Create React App instead of Next, if you are interested :-)

**Comment by pierre1590** [comment]
Thanks for support @antoniogiordano.
